export interface ProblemOption {
    label: string;
    value: string;
}

export interface StandingsRecord {
    userName: string;
    rank: string;
    score: string;
}

export interface MySubmissionsRecord {
    problemName: string;
    timeSubmitted: string;
    status: number;
    runTime: number;
    memory: string;
    languageName: string;
    testcasePassed: string;
}

export const ContestProblemsData = {
    succeeded: true,
    errors: ["string"],
    problems: [
        {
            "id": "1",
            "userId": "11",
            "user": null,
            "code": "MULTIPLES",
            "title": "#1: Multiples of 3 and 5",
            "difficulty": 1,
            "description": "Description\n\nIf we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\n\nFind the sum of all the multiples of 3 or 5 below N.\n\nInput Format\n\nFirst line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N..\n\nOutput Format\n\nFor each test case, print an integer that denotes the sum of all the multiples of 3 or 5 below N.\n\nExplanation 0\n\nFor N = 10, if we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\n\nSimilarly for N = 100, we get 2318.",
            "date": "2024-04-09T12:24:24.2694333",
            "timeLimit": 2,
            "gradeMode": 0,
            "testCases": [],
            "results": [],
            "solutions": [],
            "problemLanguages": [],
            "problemContests": null
        },
        {
            "id": "2",
            "userId": "12",
            "user": null,
            "code": "FIBONACCI",
            "title": "#2: Even Fibonacci numbers",
            "difficulty": 1,
            "description": "Description\n\nEach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.\n\nInput Format\n\nFirst line contains  that denotes the number of test cases. This is followed by  lines, each containing an integer, .\n\nOutput Format\n\nPrint the required answer for each test case.",
            "date": "2024-04-09T12:24:24.2694333",
            "timeLimit": 2,
            "gradeMode": 0,
            "testCases": [],
            "results": [],
            "solutions": [],
            "problemLanguages": [],
            "problemContests": null
        },
        {
            "id": "3",
            "userId": "13",
            "user": null,
            "code": "LARGESTPRIME",
            "title": "#3: Largest prime factor",
            "difficulty": 1,
            "description": "Description\n\nThe prime factors of 13195 are 5, 7, 13 and 29.\nWhat is the largest prime factor of a given number N?\n\nInput Format\n\nFirst line contains T, the number of test cases. This is followed by T lines each containing an integer N.\n\nOutput Format\n\nFor each test case, display the largest prime factor of N.\n\nExplanation 0\n\n-Prime factors of 10 are {2, 5}, largest is 5.\n\n-Prime factor of 17 is 17 itself, hence largest is 17.",
            "date": "2024-04-09T12:24:24.2694333",
            "timeLimit": 2,
            "gradeMode": 0,
            "testCases": [],
            "results": [],
            "solutions": [],
            "problemLanguages": [],
            "problemContests": null
        },
        {
            "id": "4",
            "userId": "14",
            "user": null,
            "code": "LARGESTPALINDROME",
            "title": "#4: Largest palindrome product",
            "difficulty": 1,
            "description": "Description\n\nA palindromic number reads the same both ways. The smallest 6 digit palindrome made from the product of two 3-digit numbers is 101101 = 143 x 707.\n\nFind the largest palindrome made from the product of two 3-digit numbers which is less than N.\n\nInput Format\n\nFirst line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.\n\nOutput Format\n\nPrint the required answer for each test case in a new line.\n\nExplanation 0\n\n- 101101 is product of 143 and 707.\n\n- 793397 is product of 869 and 913.",
            "date": "2024-04-09T12:24:24.2694333",
            "timeLimit": 2,
            "gradeMode": 0,
            "testCases": [],
            "results": [],
            "solutions": [],
            "problemLanguages": [],
            "problemContests": null
        }
    ]
}

export const problemsOpt = [
    {
        "label": "#1: Multiples of 3 and 5",
        "value": "#1: Multiples of 3 and 5",
    },
    {
        "label": "#2: Even Fibonacci numbers",
        "value": "#2: Even Fibonacci numbers",
    },
    {
        "label": "#3: Largest prime factor",
        "value": "#3: Largest prime factor",
    },
    {
        "label": "#4: Largest palindrome product",
        "value": "#4: Largest palindrome product",
    },
]

export const standings = [
    {
        "userName": "Alex911",
        "rank": "1",
        "score": "1232",
    },
    {
        "userName": "DoppoX",
        "rank": "2",
        "score": "1211",
    },
    {
        "userName": "XLLL",
        "rank": "3",
        "score": "1172",
    },
    {
        "userName": "G.G",
        "rank": "4",
        "score": "1150",
    },
    {
        "userName": "BillyBat",
        "rank": "5",
        "score": "1105",
    },
    {
        "userName": "Tom",
        "rank": "6",
        "score": "1016",
    },
    {
        "userName": "Bomber",
        "rank": "7",
        "score": "980",
    },
    {
        "userName": "NewNewMew",
        "rank": "8",
        "score": "975",
    },
    {
        "userName": "111111",
        "rank": "9",
        "score": "960",
    },
    {
        "userName": "LoLoLo",
        "rank": "10",
        "score": "930",
    },
]


export const submissions = [
    {
        "problemName": "#1: Multiples of 3 and 5",
        "timeSubmitted": "2023-03-03 18:30",
        "status": 0,
        "runTime": 8,
        "memory": "52.6",
        "languageName": "Java",
        "testcasePassed": "100",
    },
    {
        "problemName": "#2: Even Fibonacci numbers",
        "timeSubmitted": "2023-03-03 18:52",
        "status": 0,
        "runTime": 12,
        "memory": "60.6",
        "languageName": "Java",
        "testcasePassed": "100",
    },
    {
        "problemName": "#3: Largest prime factor",
        "timeSubmitted": "2023-03-03 18:30",
        "status": 0,
        "runTime": 22,
        "memory": "64.2",
        "languageName": "Java",
        "testcasePassed": "100",
    },
    {
        "problemName": "#2: Even Fibonacci numbers",
        "timeSubmitted": "2023-03-03 18:30",
        "status": 1,
        "runTime": 8,
        "memory": "50.6",
        "languageName": "Java",
        "testcasePassed": "80",
    },
    {
        "problemName": "#4: Largest palindrome product",
        "timeSubmitted": "2023-03-03 17:10",
        "status": 0,
        "runTime": 17,
        "memory": "68",
        "languageName": "Java",
        "testcasePassed": "100",
    },
    {
        "problemName": "#4: Largest palindrome product",
        "timeSubmitted": "2023-03-03 18:30",
        "status": 1,
        "runTime": 22,
        "memory": "60",
        "languageName": "Java",
        "testcasePassed": "95",
    },
]